name: ${project.name}
main: uk.protonull.smithery.Smithery
version: ${project.version}
api-version: 1.16
depend: [CivModCore]
permissions:
  smithery.admin:
    default: op
  smithery.smelt:
    default: true
  smithery.cool:
    default: true
  smithery.checktime:
    default: true
  smithery.remove:
    default: true
  smithery.inspect:
    default: op